"use client";

import { useEffect, useState } from "react";
import { ArrowRight, CheckCircle2, Eye, EyeOff, LockKeyhole, Mail } from "lucide-react";
import { createClient } from "@/lib/supabase/client";

export default function LoginPage() {
  const [showPassword,setShowPassword]=useState(false);const [loading,setLoading]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(new URLSearchParams(window.location.search).get("inactive"))setError("Esta conta está desativada. Procure um Administrador.")},[]);
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setLoading(true);setError("");const form=new FormData(event.currentTarget),email=String(form.get("email")),password=String(form.get("password"));const supabase=createClient();const result=await supabase.auth.signInWithPassword({email,password});if(result.error){setError("E-mail ou senha incorretos, ou acesso desativado.");setLoading(false);return}window.location.href="/"};
  return <main className="login-page"><section className="login-brand"><div className="login-logo"><img src="/astro-brand.jpg" alt="Astro Equipamentos Esportivos"/></div><div><span>CONTROLE FINANCEIRO INTERNO</span><h1>Decisões melhores começam com números claros.</h1><p>Vendas, custos, parcelas e caixa em um só lugar — abastecidos manualmente pela sua equipe.</p></div><ul><li><CheckCircle2/>Custos históricos preservados</li><li><CheckCircle2/>Fluxo de caixa por realização</li><li><CheckCircle2/>Acessos definidos por cargo</li></ul></section><section className="login-form-wrap"><form className="login-form" onSubmit={submit}><div className="login-mobile-logo"><img src="/astro-brand.jpg" alt="Astro"/></div><span className="login-kicker">ACESSO RESTRITO</span><h2>Bem-vindo de volta</h2><p>Entre com os dados fornecidos pelo Administrador.</p><label><span>E-mail</span><div><Mail/><input name="email" type="email" required placeholder="nome@astro.com.br"/></div></label><label><span>Senha</span><div><LockKeyhole/><input name="password" type={showPassword?"text":"password"} minLength={8} required placeholder="Sua senha"/><button type="button" onClick={()=>setShowPassword(value=>!value)}>{showPassword?<EyeOff/>:<Eye/>}</button></div></label>{error&&<div className="login-error">{error}</div>}<button className="login-submit" disabled={loading}>{loading?"Aguarde...":"Entrar no sistema"}<ArrowRight/></button><div className="login-admin-note">Novas contas são criadas pelo Administrador em <strong>Usuários e acessos</strong>.</div><small>Ambiente interno · Nenhuma conexão bancária</small></form></section></main>;
}
