"use client";

import { useCallback, useEffect, useState } from "react";
import { KeyRound, Plus, Power, PowerOff, ShieldCheck, UserRoundCog, Warehouse, X } from "lucide-react";
import type { AccessRole, UserProfile } from "@/domain/types";
import { useStore } from "./store";
import { Field } from "./ui";

const roleName:Record<AccessRole,string>={admin:"Administrador",stock_operator:"Operador de Estoque"};
const formatDate=(value?:string)=>value?new Date(value).toLocaleString("pt-BR",{dateStyle:"short",timeStyle:"short"}):"Nunca acessou";

export function AccessSettingsView(){
  const {state}=useStore();const [users,setUsers]=useState<UserProfile[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [createOpen,setCreateOpen]=useState(false);const [resetUser,setResetUser]=useState<UserProfile>();
  const load=useCallback(async()=>{setLoading(true);const response=await fetch("/api/admin/users");const result=await response.json();if(!response.ok)setError(result.error||"Não foi possível carregar os usuários.");else{setUsers(result.users);setError("")}setLoading(false)},[]);
  useEffect(()=>{void load()},[load]);
  const update=async(body:Record<string,unknown>)=>{setError("");const response=await fetch("/api/admin/users",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const result=await response.json();if(!response.ok){setError(result.error||"Não foi possível concluir a alteração.");return false}await load();return true};
  return <div className="access-page">
    <div className="access-role-grid"><article className="panel access-role-card"><ShieldCheck/><div><h3>Administrador</h3><p>Perfil para donos e gerentes. Acesso total ao financeiro, vendas, relatórios, cadastros e estoque.</p></div></article><article className="panel access-role-card"><Warehouse/><div><h3>Operador de Estoque</h3><p>Perfil para funcionários. Acesso somente a Equipamentos, Insumos e Alertas de estoque.</p></div></article></div>
    <section className="panel table-panel access-users"><div className="panel-head"><div><h3>Usuários e permissões</h3><p>Crie contas com senha temporária e controle os acessos da equipe.</p></div><button className="primary" onClick={()=>setCreateOpen(true)}><Plus/>Novo usuário</button></div>{error&&<div className="access-error">{error}</div>}{loading?<div className="access-loading">Carregando usuários...</div>:<table><thead><tr><th>Usuário</th><th>Cargo</th><th>Último acesso</th><th>Status</th><th>Ações</th></tr></thead><tbody>{users.map(user=><tr key={user.id} className={!user.active?"inactive-user":""}><td><strong>{user.fullName}</strong><span className="cell-sub">{user.email}{user.id===state.currentProfile?.id?" · Sua conta":""}</span></td><td><select value={user.role} disabled={user.id===state.currentProfile?.id||!user.active} onChange={event=>void update({action:"role",id:user.id,role:event.target.value})}><option value="admin">Administrador</option><option value="stock_operator">Operador de Estoque</option></select></td><td>{formatDate(user.lastSignInAt)}</td><td><span className={`user-status ${user.active?"active":"inactive"}`}>{user.active?"Ativo":"Desativado"}</span>{user.mustChangePassword&&user.active&&<small className="temporary-password">Troca de senha pendente</small>}</td><td><div className="user-actions"><button title="Definir nova senha temporária" onClick={()=>setResetUser(user)}><KeyRound/></button>{user.id!==state.currentProfile?.id&&(user.active?<button className="deactivate" title="Desativar acesso" onClick={()=>void update({action:"deactivate",id:user.id})}><PowerOff/></button>:<button className="activate" title="Reativar acesso" onClick={()=>void update({action:"activate",id:user.id})}><Power/></button>)}</div></td></tr>)}</tbody></table>}</section>
    {createOpen&&<CreateUserModal close={()=>setCreateOpen(false)} saved={load}/>} {resetUser&&<ResetPasswordModal user={resetUser} close={()=>setResetUser(undefined)} save={update}/>} 
  </div>
}

function CreateUserModal({close,saved}:{close:()=>void;saved:()=>Promise<void>}){
  const [saving,setSaving]=useState(false);const [error,setError]=useState("");const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);setError("");const form=new FormData(event.currentTarget);const response=await fetch("/api/admin/users",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({fullName:form.get("name"),email:form.get("email"),password:form.get("password"),role:form.get("role")})});const result=await response.json();setSaving(false);if(!response.ok){setError(result.error||"Não foi possível criar a conta.");return}await saved();close()};
  return <div className="modal-backdrop"><form className="modal user-modal" onSubmit={submit}><div className="modal-head"><div><h3>Novo usuário</h3><p>O funcionário deverá trocar a senha temporária no primeiro acesso.</p></div><button type="button" onClick={close}><X/></button></div><div className="form-grid"><Field label="Nome completo"><input name="name" required/></Field><Field label="Cargo"><select name="role"><option value="stock_operator">Operador de Estoque</option><option value="admin">Administrador</option></select></Field><Field label="E-mail"><input name="email" type="email" required/></Field><Field label="Senha temporária"><input name="password" type="password" minLength={8} maxLength={72} required/></Field></div>{error&&<div className="modal-form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving}><UserRoundCog/>{saving?"Criando...":"Criar usuário"}</button></div></form></div>
}

function ResetPasswordModal({user,close,save}:{user:UserProfile;close:()=>void;save:(body:Record<string,unknown>)=>Promise<boolean>}){
  const [saving,setSaving]=useState(false);const [error,setError]=useState("");const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget),password=String(form.get("password")),confirmation=String(form.get("confirmation"));if(password!==confirmation){setError("As senhas não coincidem.");return}setSaving(true);if(await save({action:"reset_password",id:user.id,password}))close();else setError("Não foi possível alterar a senha.");setSaving(false)};
  return <div className="modal-backdrop"><form className="modal reset-modal" onSubmit={submit}><div className="modal-head"><div><h3>Nova senha temporária</h3><p>{user.fullName} deverá alterá-la no próximo acesso.</p></div><button type="button" onClick={close}><X/></button></div><div className="form-grid"><Field label="Senha temporária"><input name="password" type="password" minLength={8} maxLength={72} required/></Field><Field label="Confirmar senha"><input name="confirmation" type="password" minLength={8} maxLength={72} required/></Field></div>{error&&<div className="modal-form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving}><KeyRound/>{saving?"Salvando...":"Definir senha"}</button></div></form></div>
}
