"use client";

import { Mail, MapPin, Phone, Plus, Search, UserRound, UsersRound, X } from "lucide-react";
import { useState } from "react";
import { brl, calculateSale, pendingTotal } from "@/domain/finance";
import type { Customer, Seller } from "@/domain/types";
import { useStore } from "./store";
import { Field } from "./ui";

export function DirectoryView({mode}:{mode:"customers"|"suppliers"|"sellers"}) {
  const {state,addCustomer,addSeller}=useStore(); const [modal,setModal]=useState(false);
  if(mode==="customers") return <><div className="view-actions"><div className="input-search"><Search size={17}/><input placeholder="Buscar cliente..."/></div><button className="primary" onClick={()=>setModal(true)}><Plus size={16}/>Novo cliente</button></div><div className="card-directory">{state.customers.map(customer=>{const sales=state.sales.filter(sale=>sale.customerId===customer.id),total=sales.reduce((value,sale)=>value+calculateSale(sale).netCents,0),pending=sales.reduce((value,sale)=>value+pendingTotal(sale.installments),0);return <article className="directory-card" key={customer.id}><div className="directory-top"><div className="big-initials">{customer.company.slice(0,2).toUpperCase()}</div><div><h3>{customer.company}</h3><p>{customer.name}</p></div></div><div className="contact-lines"><span><MapPin/>{customer.city || "Cidade não informada"}{customer.state?`, ${customer.state}`:""}</span><span><Phone/>{customer.phone || "Telefone não informado"}</span><span><Mail/>{customer.email || "E-mail não informado"}</span></div><div className="directory-metrics"><div><span>Total comprado</span><strong>{brl(total)}</strong></div><div><span>A receber</span><strong>{brl(pending)}</strong></div></div></article>})}</div>{modal&&<CustomerModal close={()=>setModal(false)} save={addCustomer}/>}</>;
  if(mode==="sellers") return <><div className="view-actions"><div/><button className="primary" onClick={()=>setModal(true)}><Plus size={16}/>Novo vendedor</button></div><div className="card-directory">{state.sellers.map(seller=>{const sales=state.sales.filter(sale=>sale.sellerId===seller.id),totals=sales.map(calculateSale);return <article className="directory-card" key={seller.id}><div className="directory-top"><div className="big-initials seller"><UserRound/></div><div><h3>{seller.name}</h3><p>Vendedor ativo</p></div></div><div className="contact-lines"><span><Phone/>{seller.phone||"Telefone não informado"}</span><span><Mail/>{seller.email||"E-mail não informado"}</span></div><div className="directory-metrics three"><div><span>Vendas</span><strong>{sales.length}</strong></div><div><span>Faturamento</span><strong>{brl(totals.reduce((sum,item)=>sum+item.netCents,0))}</strong></div><div><span>Comissão</span><strong>{brl(totals.reduce((sum,item)=>sum+item.commissionCents,0))}</strong></div></div></article>})}</div>{modal&&<SellerModal close={()=>setModal(false)} save={addSeller}/>}</>;
  const suppliers=[...new Set(state.expenses.map(expense=>expense.supplier))];return <div className="card-directory">{suppliers.map(name=>{const expenses=state.expenses.filter(expense=>expense.supplier===name);return <article className="directory-card" key={name}><div className="directory-top"><div className="big-initials supplier"><UsersRound/></div><div><h3>{name}</h3><p>{expenses[0]?.category}</p></div></div><div className="directory-metrics"><div><span>Despesas</span><strong>{expenses.length}</strong></div><div><span>Total contratado</span><strong>{brl(expenses.reduce((sum,expense)=>sum+expense.totalCents,0))}</strong></div></div></article>})}</div>;
}

function CustomerModal({close,save}:{close:()=>void;save:(customer:Customer)=>Promise<void>}) { const [saving,setSaving]=useState(false); const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);const form=new FormData(event.currentTarget);try{await save({id:crypto.randomUUID(),name:String(form.get("name")),company:String(form.get("company")),document:String(form.get("document")),phone:String(form.get("phone")),email:String(form.get("email")),city:String(form.get("city")),state:String(form.get("state")).toUpperCase()});close()}finally{setSaving(false)}};return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><h3>Novo cliente</h3><p>Cadastre os dados comerciais e de contato.</p></div><button type="button" onClick={close}><X/></button></div><div className="form-grid"><Field label="Nome do contato"><input name="name" required/></Field><Field label="Empresa / razão social"><input name="company" required/></Field><Field label="CPF / CNPJ"><input name="document"/></Field><Field label="Telefone / WhatsApp"><input name="phone"/></Field><Field label="E-mail"><input name="email" type="email"/></Field><Field label="Cidade"><input name="city"/></Field><Field label="Estado"><input name="state" maxLength={2}/></Field></div><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Salvando...":"Salvar cliente"}</button></div></form></div> }
function SellerModal({close,save}:{close:()=>void;save:(seller:Seller)=>Promise<void>}) { const [saving,setSaving]=useState(false); const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();setSaving(true);const form=new FormData(event.currentTarget);try{await save({id:crypto.randomUUID(),name:String(form.get("name")),phone:String(form.get("phone")),email:String(form.get("email")),active:true});close()}finally{setSaving(false)}};return <div className="modal-backdrop"><form className="modal" onSubmit={submit}><div className="modal-head"><div><h3>Novo vendedor</h3><p>Cadastre o responsável pelas vendas.</p></div><button type="button" onClick={close}><X/></button></div><div className="form-grid"><Field label="Nome"><input name="name" required/></Field><Field label="Telefone"><input name="phone"/></Field><Field label="E-mail"><input name="email" type="email"/></Field></div><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving}>{saving?"Salvando...":"Salvar vendedor"}</button></div></form></div> }
