"use client";

import { useEffect, useMemo, useState } from "react";
import { AlertTriangle, Boxes, CheckCircle2, Layers3, Pencil, Plus, Save, Search, Trash2, X } from "lucide-react";
import { brl, toCents } from "@/domain/finance";
import type { ProductInput } from "@/domain/types";
import { useStore } from "./store";
import { Field } from "./ui";

export function ProductInputsView() {
  const {state,addProductInput,updateProductInput,removeProductInput,updateProductCost,updateInventoryStock}=useStore();
  const [selectedId,setSelectedId]=useState(""); const [saving,setSaving]=useState(false); const [updated,setUpdated]=useState(false); const [search,setSearch]=useState(""); const [editing,setEditing]=useState<ProductInput>();
  useEffect(()=>{if(!selectedId&&state.products[0])setSelectedId(state.products[0].id)},[state.products,selectedId]);
  const selected=state.products.find(product=>product.id===selectedId);
  const inputs=state.productInputs.filter(input=>input.productId===selectedId&&(!search||(input.name+input.code).toLowerCase().includes(search.toLowerCase())));
  const allSelectedInputs=state.productInputs.filter(input=>input.productId===selectedId);
  const composedCost=useMemo(()=>allSelectedInputs.reduce((sum,input)=>sum+Math.round(input.quantity*input.unitCostCents),0),[allSelectedInputs]);
  const knownNames=[...new Set(state.productInputs.map(input=>input.name))];
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!selected)return;const formElement=event.currentTarget;setSaving(true);const form=new FormData(formElement);const code=String(form.get("code")||"").trim();const name=String(form.get("name")).trim();const unit=String(form.get("unit"));const existing=state.productInputs.find(input=>(code&&input.code?.toLowerCase()===code.toLowerCase())||(!code&&input.name.toLowerCase()===name.toLowerCase()&&input.unit===unit));try{await addProductInput({id:crypto.randomUUID(),productId:selected.id,inventoryItemId:existing?.inventoryItemId||crypto.randomUUID(),code:code||undefined,name,unit,quantity:Number(form.get("quantity"))||1,unitCostCents:existing?.unitCostCents??toCents(String(form.get("cost"))),currentStock:existing?.currentStock??Number(form.get("stock")||0),minimumStock:existing?.minimumStock??Number(form.get("minimumStock")||0),createdAt:new Date().toISOString()});formElement.reset();setUpdated(false)}finally{setSaving(false)}};
  const applyCost=async()=>{if(!selected||!allSelectedInputs.length)return;setSaving(true);try{await updateProductCost(selected.id,composedCost);setUpdated(true)}finally{setSaving(false)}};
  if(!state.products.length)return <div className="panel inputs-empty"><Boxes/><h3>Cadastre um equipamento primeiro</h3><p>A ficha de insumos será vinculada aos equipamentos do catálogo.</p></div>;
  return <div className="bom-page">
    <div className="bom-actions"><button className="primary" disabled={!allSelectedInputs.length||saving||composedCost===selected?.costCents} onClick={()=>void applyCost()}>{updated?<CheckCircle2/>:<Save/>}{updated?"Custo atualizado":"Salvar custo calculado"}</button><div className="bom-selected-title"><span>FICHA TÉCNICA</span><strong>{selected?.sku} — {selected?.name}</strong></div></div>
    <section className="panel bom-sheet">
      <nav className="bom-tabs"><button>Produto</button><button>Preços</button><button>Custos</button><button className="active">Insumos</button><button>Histórico</button></nav>
      <div className="bom-product-row"><Field label="Equipamento"><select value={selectedId} onChange={event=>{setSelectedId(event.target.value);setUpdated(false)}}>{state.products.map(product=><option key={product.id} value={product.id}>{product.sku} — {product.name}</option>)}</select></Field><div><span>Custo atual</span><strong>{brl(selected?.costCents||0)}</strong></div><div className="calculated"><span>Custo calculado</span><strong>{brl(composedCost)}</strong></div><div><span>Diferença</span><strong className={composedCost>(selected?.costCents||0)?"negative-text":"positive-text"}>{composedCost-(selected?.costCents||0)>=0?"+ ":"- "}{brl(Math.abs(composedCost-(selected?.costCents||0)))}</strong></div></div>
      <form className="bom-add-row stock-enabled" onSubmit={submit}><Field label="Código"><input name="code" placeholder="Ex: 329"/></Field><Field label="Insumo / descrição"><input name="name" list="known-inputs" required placeholder="Ex: Motor inversor WEG"/><datalist id="known-inputs">{knownNames.map(name=><option key={name} value={name}/>)}</datalist></Field><Field label="Qtd. por equipamento"><input name="quantity" type="number" min="0.0001" step="0.0001" defaultValue="1" required/></Field><Field label="Unidade"><select name="unit"><option value="unidade">UNIDADE</option><option value="peça">PEÇA</option><option value="conjunto">CONJUNTO</option><option value="kg">KG</option><option value="m">METRO</option><option value="m²">M²</option><option value="l">LITRO</option><option value="kit">KIT</option><option value="serviço">SERVIÇO</option></select></Field><Field label="Valor unitário"><input name="cost" required placeholder="R$ 0,00"/></Field><Field label="Estoque atual"><input name="stock" type="number" step="0.0001" min="0" defaultValue="0" required/></Field><Field label="Estoque mínimo"><input name="minimumStock" type="number" step="0.0001" min="0" defaultValue="0" required/></Field><button className="primary" disabled={saving}><Plus/>Adicionar</button></form>
      <div className="bom-table-tools"><div className="input-search"><Search/><input value={search} onChange={event=>setSearch(event.target.value)} placeholder="Buscar na composição..."/></div><span>Exibindo {inputs.length} de {allSelectedInputs.length} insumos</span></div>
      <div className="table-panel bom-table stock-table"><table><thead><tr><th>Código</th><th>Descrição</th><th>Qtd. por equipamento</th><th>Unidade</th><th>Valor unitário</th><th>Total</th><th>Estoque atual / mínimo</th><th>Situação</th><th/></tr></thead><tbody>{inputs.map(input=><tr key={input.id}><td>{input.code||"—"}</td><td><strong>{input.name}</strong></td><td>{input.quantity.toLocaleString("pt-BR",{maximumFractionDigits:4})}</td><td>{input.unit.toUpperCase()}</td><td>{brl(input.unitCostCents)}</td><td><strong>{brl(Math.round(input.quantity*input.unitCostCents))}</strong></td><td><StockEditor input={input} save={updateInventoryStock}/></td><td>{input.currentStock<=input.minimumStock?<span className="stock-status low"><AlertTriangle/>Repor estoque</span>:<span className="stock-status ok"><CheckCircle2/>Normal</span>}</td><td><div className="input-row-actions"><button className="bom-edit" title="Editar insumo" onClick={()=>setEditing(input)}><Pencil/></button><button className="bom-remove" title="Remover insumo" onClick={()=>void removeProductInput(input.id)}><Trash2/></button></div></td></tr>)}</tbody></table>{!inputs.length&&<div className="inputs-no-lines"><Layers3/><strong>Nenhum insumo nesta composição</strong><span>Use a linha acima para adicionar o primeiro componente.</span></div>}</div>
      <footer className="bom-footer"><div><span>Quantidade de itens</span><strong>{allSelectedInputs.length}</strong></div><div><span>Custo total dos insumos</span><strong>{brl(composedCost)}</strong></div><button className="primary" disabled={!allSelectedInputs.length||saving||composedCost===selected?.costCents} onClick={()=>void applyCost()}><Save/>{updated?"Custo atualizado":"Usar como custo do equipamento"}</button></footer>
    </section>
    <div className="inputs-history-note"><CheckCircle2/><span>O custo só é alterado ao salvar. O valor anterior permanece no histórico e nenhuma venda antiga é recalculada.</span></div>
    {editing&&<EditInputModal input={editing} close={()=>setEditing(undefined)} save={updateProductInput}/>}
  </div>;
}

function EditInputModal({input,close,save}:{input:ProductInput;close:()=>void;save:(input:ProductInput)=>Promise<void>}){
  const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  const submit=async(event:React.FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);setSaving(true);setError("");try{await save({...input,code:String(form.get("code")||"").trim()||undefined,name:String(form.get("name")).trim(),quantity:Number(form.get("quantity")),unit:String(form.get("unit")),unitCostCents:toCents(String(form.get("cost"))),currentStock:Number(form.get("stock")),minimumStock:Number(form.get("minimumStock")),notes:String(form.get("notes")||"").trim()||undefined});close()}catch{setError("Não foi possível salvar as alterações do insumo.")}finally{setSaving(false)}};
  return <div className="modal-backdrop"><form className="modal input-edit-modal" onSubmit={submit}><div className="modal-head"><div><h3>Editar insumo</h3><p>Atualize os dados da composição e do estoque.</p></div><button type="button" onClick={close}><X/></button></div><div className="form-grid"><Field label="Código"><input name="code" defaultValue={input.code}/></Field><Field label="Insumo / descrição"><input name="name" defaultValue={input.name} required/></Field><Field label="Qtd. por equipamento"><input name="quantity" type="number" min="0.0001" step="0.0001" defaultValue={input.quantity} required/></Field><Field label="Unidade"><select name="unit" defaultValue={input.unit}><option value="unidade">UNIDADE</option><option value="peça">PEÇA</option><option value="conjunto">CONJUNTO</option><option value="kg">KG</option><option value="m">METRO</option><option value="m²">M²</option><option value="l">LITRO</option><option value="kit">KIT</option><option value="serviço">SERVIÇO</option></select></Field><Field label="Valor unitário"><input name="cost" defaultValue={(input.unitCostCents/100).toLocaleString("pt-BR",{minimumFractionDigits:2,maximumFractionDigits:2})} required/></Field><Field label="Estoque atual"><input name="stock" type="number" min="0" step="0.0001" defaultValue={input.currentStock} required/></Field><Field label="Estoque mínimo"><input name="minimumStock" type="number" min="0" step="0.0001" defaultValue={input.minimumStock} required/></Field><Field label="Observações"><input name="notes" defaultValue={input.notes}/></Field></div>{error&&<div className="modal-form-error">{error}</div>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancelar</button><button className="primary" disabled={saving}><Save/>{saving?"Salvando...":"Salvar alterações"}</button></div></form></div>
}

function StockEditor({input,save}:{input:import("@/domain/types").ProductInput;save:(id:string,current:number,minimum:number,notes?:string)=>Promise<void>}){
  const [current,setCurrent]=useState(input.currentStock);const [minimum,setMinimum]=useState(input.minimumStock);const [saving,setSaving]=useState(false);
  useEffect(()=>{setCurrent(input.currentStock);setMinimum(input.minimumStock)},[input.currentStock,input.minimumStock]);
  const changed=current!==input.currentStock||minimum!==input.minimumStock;
  const submit=async()=>{setSaving(true);try{await save(input.inventoryItemId,current,minimum,"Ajuste manual na ficha de insumos")}finally{setSaving(false)}};
  return <div className="stock-editor"><label><span>Atual</span><input type="number" step="0.0001" value={current} onChange={event=>setCurrent(Number(event.target.value))}/></label><label><span>Mín.</span><input type="number" min="0" step="0.0001" value={minimum} onChange={event=>setMinimum(Number(event.target.value))}/></label><button title="Salvar estoque" disabled={!changed||saving} onClick={()=>void submit()}><Save/></button></div>
}
